name: grocery_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  country_code_picker: ^3.4.1
  flutter_intl_phone_field: ^0.0.7
  google_sign_in: ^6.3.0
  http: ^1.6.0
  get: ^4.7.3
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  go_router: ^17.0.0
  carousel_slider: ^5.1.1
  lottie: ^3.3.2
  icons_plus: ^5.0.0
  animated_text_kit: ^4.3.0
  shimmer: ^3.0.0
  collection: ^1.19.1
  qr_flutter: ^4.0.0
  intl: ^0.20.2
  get_storage: ^2.1.1
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.12.0
  image_picker: ^1.2.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  url_launcher: ^6.3.2
  pinput: ^6.0.1
  # url_launcher: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/splash_screen/
    - assets/images/
    - assets/images/payment/
    - assets/images/logo/
    - assets/images/appBar/
    - assets/images/appBar/Local_brand/
    - assets/images/banner/
    - assets/fonts/
    - assets/fonts/gilroy/
    - assets/images/grocery_images/
    - assets/images/categories_images/
    - assets/images/beverages_images/
    - assets/icons/
    - assets/icons/account_icons/
    - assets/icons/order_accepted_icon.svg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets\fonts\gilroy\Gilroy-Bold.otf
        - asset: assets\fonts\gilroy\Gilroy-Regular.ttf
        - asset: assets\fonts\gilroy\Gilroy-SemiBold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
